Us04
WildCodeSchool/orleans-php-2003-project-aon pull request #4
Opened 2020-04-15 17:49 UTC by Melusine45

SP01US04 Home Event

Creation du fichier _event.html.twig pour la vue dans lequel on doit retrouver le titre de la section, le nom de l'évènement, le lieu, la date, une photo et une description.
Ce dernier apparaît en fonction de la date la plus recente.

Creation du fichier EventManager. On y retrouve la requête permettant d'afficher le dernier évènement en date. 

Modification du HomeController afin d'indiquer à la vue quelle méthode utiliser pour afficher la dernière actualité en date.

Modification du fichier CSS de base car la taille des polices mises par défaut étaient trop grosses.

Ajout d'un fichier homepageevent.css pour permettre une petite mise en page (en plus du bootstrap).

Ajouts de photos diverses dans le fichier images servant d'illustrations à la homepage (et à terme à la page actualité).

Insertion de l'inclusion du fichier _event.html dans le fichier index.html.

2020-04-15 20:28 UTC, mayard689 requested changes
_event.html.twig :
- Dans la balise img, il faudrait mettre un « alt » au cas ou l’image ne puisse pas s’afficher.
- Git indique qu’il manque un retour à la ligne à la fin de la dernière ligne.

Homepageevent.css :
- De mon coté j’ai utilisé homepage_activity. Il faudrait soit que j’enlève l’underscore soit que tu en ajoutes un.
- Git indique qu’il manque un retour à la ligne à la fin de la dernière ligne.

HomeController.php et EventManager.php : 
- Les deux fichiers commencent par un commentaire indiquant que c’est soit Aurélien soit Sylvain qui a créé le fichier il y a1 ou 2 ans. Il faudrait mettre à jour ces infos.
Rqe : moi même j’ai oublié de mettre à jour car phpStorm « cache » ces infos dans l’éditeur de texte.

2020-04-16 07:32 UTC, mayard689 submitted a review, later dismissed
Previous comments have been taken into account. OK for merge.

2020-04-16 08:05 UTC, mayard689 submitted a review, later dismissed

2020-04-16 08:16 UTC, mayard689 approved these changes
All comments have been taken into account. Ok for merge.

2020-04-16 11:21 UTC, ldupas approved these changes
us04 approved

2020-04-16 11:21 UTC, merged