Sp2 us33 delete event bis
WildCodeSchool/orleans-php-2003-project-aon pull request #46
Opened 2020-04-23 16:04 UTC by JudgeBurger

Add Delete Function. 
Add Button delete.

2020-04-23 16:26 UTC, Emmanuelle-Mendels submitted a review, later dismissed

2020-04-24 06:19 UTC, ldupas requested changes
Pour vous éviter un fix, souci de majuscule (cohérence).

2020-04-24 06:19 UTC, ldupas commented on src/View/Admin/_eventAdmin.html.twig
> +                <th>location</th>
Pas de majuscule ici ?

2020-04-24 06:26 UTC, Emmanuelle-Mendels submitted a review, later dismissed
modif ok

2020-04-24 06:40 UTC, Emmanuelle-Mendels approved these changes
conflits ok

2020-04-24 07:18 UTC, ldupas approved these changes
Ok.

2020-04-24 07:19 UTC, merged