Sp3 us28 admin activity
WildCodeSchool/orleans-php-2003-project-aon pull request #50
Opened 2020-04-27 15:48 UTC by Melusine45

Ajout de la page administration des activités

2020-04-27 17:04 UTC, maoherve submitted a review, later dismissed

2020-04-28 06:30 UTC, ldupas requested changes

2020-04-28 06:30 UTC, ldupas commented on src/Model/ActivityManager.php
> +    public function selectAllActivitiesforAdmin(): array
Problème de camelCase !

2020-04-28 06:30 UTC, ldupas commented on src/Controller/AdminController.php
> +        $activities = $activityManager->selectAllActivitiesforAdmin();
Problème de camelCase !

2020-04-28 06:30 UTC, ldupas commented on src/View/Admin/_eventAdmin.html.twig
> +            <h2>Gestion des évenements</h2>
événements

2020-04-28 06:58 UTC, Melusine45 commented on src/Model/ActivityManager.php
> +    public function selectAllActivitiesforAdmin(): array
c'est corrigé

2020-04-28 06:58 UTC, Melusine45 commented on src/Controller/AdminController.php
> +        $activities = $activityManager->selectAllActivitiesforAdmin();
correction ok

2020-04-28 06:59 UTC, Melusine45 commented on src/View/Admin/_eventAdmin.html.twig
> +            <h2>Gestion des évenements</h2>
ajout des accents sur le mot évènement à 3 reprises

2020-04-28 07:00 UTC, maoherve approved these changes

2020-04-28 08:59 UTC, ldupas approved these changes
Corrections ok !

2020-04-28 08:59 UTC, merged